name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'

autolabeler:
  - label: 'bug'
    branch:
      - '/fix.+/'
    title:
      - '/fix/i'
    body:
      - '/BUG/'
  - label: 'enhancement'
    title:
      - '/MVP1-[0-9]{1,4}.+/i'
    branch:
      - '/feature.+/'
      - '/mvp.+/'
    body:
      - '/MVP1-[0-9]{1,4}.+/i'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
    title:
      - '/chore/i'
    body:
      - '/chore/i'
      - '/script/i'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Release Notes

  $CHANGES